### ISSUE TITLE
[Question] Android Pie port

### ISSUE THREAD

**Issue by Noobzik** [Magisk-Modules-Repo/oneplus3simnfc#2]
I had tried myself to change the lines value on a Android Pie build but it doesn't seems to work, and it broke the NFC toggle.

I assume that the replaced APK is from the the one of this repo. The APK is force closing at every reboot.

So I was wondering if there is a way to make this module be compatible to android pie ?

**Comment by mk5566** [comment]
Cause I don't have pie rom yet, I'll check if there are other modification needed for pie

**Comment by heipidage** [comment]
9.0已经出来了 麻烦试试看能否用上。谢谢！

**Comment by mk5566** [comment]
> 9.0已经出来了 麻烦试试看能否用上。谢谢！
待我拿到rom後會試試看
I'll check if I can get the pie rom, I'll update to Magisk 19 first and update to pie when I moved to pie, cause I only have one phone and it's super important to me (i have nfc for many locks and authenticator, payments etc.) so I will not move to new system if I'm sure it's worked

**Comment by mk5566** [comment]
Updated to OOS Pie
